[versions]
paper-api = "1.21.11-R0.1-SNAPSHOT"
shadow = "8.3.0"
run-paper = "2.3.0"
paperweight-userdev = "2.0.0-beta.19"

[libraries]
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper-api" }

[plugins]
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "run-paper" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
paperweight-userdev = { id = "io.papermc.paperweight.userdev", version.ref = "paperweight-userdev" }